
import { Provider } from 'react-redux';
import store from '../../redux/store';
import Nav from '../app/components/nav/nav';
import Footer from '../app/components/footer/footer';
import ClientLayout from './ClientLayout';

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "e-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" />
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientLayout>
          {/* Optional: If you have a navigation and footer that should be globally available */}
          
          {children}
          
        </ClientLayout>
      </body>
    </html>
  );
}
